version: '3.8'

volumes:
  elastic:

services:

  elasticsearch:
    image: elasticsearch:8.4.3
    container_name: elasticsearch
    restart: always
    ports:
      - '9200:9200'
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 128M
    volumes:
    - elastic:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.4.3
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
